Feature/5751 add spider diagram to map
aodn/aodn-portal-v2 pull request #109
Opened 2024-08-01 07:44 UTC by NekoLyn

2024-08-02 00:17 UTC, utas-raymondng requested changes
Minor comment

2024-08-02 00:17 UTC, utas-raymondng commented on src/components/map/mapbox/component/SpiderDiagram.tsx
> +      const generateSpiderLegParams = (count: number) => {
Move this out of this function as it is pretty much fixed

2024-08-02 00:18 UTC, utas-raymondng commented
Few more comments but can fixed in next iteration, please raise tickets to capture these and other comments after the end of iteration review

1. I think we can reduce the zoom level a bit more so we can see the spider earlier
2. Once the spider appears, if you zoom out then the spider still there but keep reducing, that is spider do not disappear
3. Very good the color change on end node thanks.

I am ok to approve the PR once the comment inside the code addressed

2024-08-02 00:20 UTC, utas-raymondng requested changes
Once more minor comment

2024-08-02 00:20 UTC, utas-raymondng commented on src/components/map/mapbox/component/SpiderDiagram.tsx
> +  spiderifyFromZoomLevel: 11,
May be try change to 8 instead of 11

2024-08-02 02:05 UTC, NekoLyn commented
> Few more comments but can fixed in next iteration, please raise tickets to capture these and other comments after the end of iteration review
> 
> 1. I think we can reduce the zoom level a bit more so we can see the spider earlier
> 2. Once the spider appears, if you zoom out then the spider still there but keep reducing, that is spider do not disappear
> 3. Very good the color change on end node thanks.
> 
> I am ok to approve the PR once the comment inside the code addressed

Thanks Raymond! I agree to spiderify earlier, but it may take some time to adjust the function of calculating the radius of the spider diagram and legs/pins size to scale up/down the diagram when changing the spiderifyFromZoomLevel.

For the second point I will fix it by making the unspiderify more sensitive to the zoom out (for now it will disappear with zoom out but not so quickly) So I will raise another ticket to fix it together with other function/style issues of spider diagram in next iteration.

2024-08-02 02:34 UTC, utas-raymondng approved these changes
LGTM

2024-08-02 02:34 UTC, merged

2024-08-02 02:35 UTC, utas-raymondng commented
Please raise ticket for remain change and put links here thanks

2024-08-08 05:50 UTC, NekoLyn commented
> Please raise ticket for remain change and put links here thanks

 A ticket to adjust the variable spiderifyFromZoomLevel to make the spiderify appear more earlier https://github.com/aodn/backlog/issues/5810