Feature/5706 add associated records
aodn/aodn-portal-v2 pull request #111
Opened 2024-08-02 04:56 UTC by HavierD

2024-08-05 06:07 UTC, vietnguyengit requested changes
code are good, but just naming stuff to address as usual @HavierD

2024-08-05 06:07 UTC, vietnguyengit commented on src/components/list/listItem/CollapseItem.tsx
> +export default CollapseItem;
you have "PlainCollapseList" in the other file, why this isn't "PlainCollapseItem" but just "CollapseItem" ? What happens if you have "CollapseItem" and "CollapseList", the word "plain" is really confusing to me.

2024-08-05 06:07 UTC, vietnguyengit commented on src/components/list/AssociatedRecordList.tsx
> +export default AssociatedRecordList;
LGTM

2024-08-06 00:33 UTC, HavierD commented on src/components/list/listItem/PlainTextItem.tsx
> +interface PlainTextItemProps {
Thank you. At the beginning, i decided to name these components on detail page like: PlainText, MediaText, etc.. but then i changed the implementation so the "Plain" prefix looks strange. I will remove it.

2024-08-06 00:39 UTC, vietnguyengit commented on src/components/list/listItem/PlainTextItem.tsx
> +interface PlainTextItemProps {
cool, they are all just "text" so it's good that you don't have a bunch of different "text" components.

2024-08-06 00:46 UTC, vietnguyengit approved these changes

2024-08-06 00:46 UTC, merged