Feature/5872 add loading icon
aodn/aodn-portal-v2 pull request #146
Opened 2024-09-06 03:14 UTC by HavierD

The loading modal is only used in `searchpage`. May also be useful for other pages, but not implemented in this PR. I just used a basic progress circle. They design will change in the future and at that time we only need to replace the icon.

2024-09-10 07:41 UTC, HavierD commented
some tests were also skipped for now. will fix later

2024-09-10 23:19 UTC, utas-raymondng requested changes
Click the description on the list view, it shows the spatial extents but the loading keeps without exit

2024-09-10 23:19 UTC, utas-raymondng commented on src/components/loading/LoadingEmitter.ts
> +export default loadingEmitter;
Prefer not export this emitter directly but export function that interact with it. Therefore you can enforce event type and function type for the on and off function.

2024-09-11 05:27 UTC, utas-raymondng approved these changes
LGTM

2024-09-11 05:43 UTC, merged