Feature/5904 update filter UI
aodn/aodn-portal-v2 pull request #188
Opened 2024-10-04 05:15 UTC by NekoLyn

For now just add simple tooltips for filters

TODO: wait for feedback from Vicky about ticket task "Tooltips for all other filters"

2024-10-04 06:20 UTC, HavierD requested changes

2024-10-04 06:20 UTC, HavierD commented on src/components/common/charts/TimeRangeBarChart.tsx
> +          label: "Year", // x-axis label
if the date range become small, the x-axis will become to "month", and if even smaller, the x-axis will be "day"

2024-10-04 06:20 UTC, HavierD commented on src/components/common/filters/FilterSection.tsx
> +const renderTittle = (title: string) => (
no need to extract it. title of tooltip can be set to `undefined`

2024-10-08 22:37 UTC, HavierD commented
because of the iteration review meeting, i will takeover this branch

2024-10-09 00:36 UTC, utas-raymondng approved these changes
LGTM

2024-10-09 01:21 UTC, merged